name: Auto-merge dependency updates
on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "ORCA CI"
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    uses: acquia/.github/.github/workflows/automerge.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
